### PR TITLE
#482: Smoke Testcase for the endless loop because of white-space hand…

### PR DESCRIPTION
**Pull request by rototor**
…ling.

It demonstrates the bug in #482, a endless loop while trying to break a line. Should be included to detect regressions with that in future.

### CODE REVIEW

**Comment by rototor** [comment]
This is no longer a smoke test, but also provides a fix for this problem which seems to work and not break any other test.

**Comment by syjer** [comment]
hi @rototor , I may be wrong, but I think it will still fail if the string is larger than 1 but contains only SOFT_HYPHEN characters.

I would guess for each input string, we should reduce it to always have only one consecutive SOFT_HYPHEN .

**Comment by rototor** [comment]
@syjer You are right, I extended the testcase and the fix to also handle that cases.

**Comment by danfickle** [comment]
Thanks both of you. That would have taken me ages to find.

**Pull request merged**
