### PR TITLE
Add support for max-width and max-height properties on img elements

### PR DESCRIPTION
**Pull request by achuinard**
This commit should allow PDF rendering to support max-width and max-height properties on img elements.

### CODE REVIEW

**Comment by danfickle** [comment]
Perfect! Thanks @achuinard 

Merging now.

**Comment by achuinard** [comment]
Thanks. I thought that the best place to put this might have been in
BlockBox. Are images rendered as a BlockBox? Why didn't the max width and
max height properties get taken into account already?

**Comment by danfickle** [comment]
Images are rendered as special replaced elements (like form controls). I think this was how it was specified in an old HTML standard. We might have to revisit this if we want to apply other CSS on the img element such as transform.

**Comment by achuinard** [comment]
Sounds good. How does the release cycle work? Will RC8 be pushed to the repository?

**Comment by danfickle** [comment]
I'd prefer to not make a release so soon after the last.
Can you get away with wrapping the image in a block?

``` html
<div style="max-width: 80px;">
  <img src="image.png" alt="title" style="width: 100%;"/>
</div>
```

**Comment by achuinard** [comment]
Can you release the new version to Maven?

**Comment by danfickle** [comment]
Hi @achuinard 
I've got some uncommitted code for CSS transforms that I'm working on. Can you wait a couple of days or do you need a release for Monday?

**Comment by achuinard** [comment]
I can wait til end of week at latest.

**Pull request merged**
