### PR TITLE
fix rtl numeric list

### LINKED ISSUE #645: Numbered lists: numbers rendered after text in RTL languages
Related to #270 - which dealt with a similar issue with bulleted lists, and was solved. 

Reproduce:
Take the following html:
```html
<html dir="rtl">
   <body dir="rtl">
   <ol>
      <li>דבר ראשון</li>
      <li>דבר שני</li>
      <li>דבר שלישי</li>
   </ol>
   </body>
</html>
```

And render it with the following code:
```java
try (OutputStream os = new FileOutputStream("output.pdf")) {
    PdfRendererBuilder builder = new PdfRendererBuilder();
    builder.useUnicodeBidiSplitter(new ICUBidiSplitter.ICUBidiSplitterFactory());
    builder.useUnicodeBidiReorderer(new ICUBidiReorderer());
    builder.defaultTextDirection(BaseRendererBuilder.TextDirection.RTL);
    builder.withUri("file:///path/to/html");
    builder.toStream(os);
    builder.run();
} catch (URISyntaxException e) {
    e.printStackTrace();
}
```

Get the following PDF:
image

The numbers are expected to be to the right of the text, like so:
image

### PR DESCRIPTION
**Pull request by johnnyaug**
Closes #645

### CODE REVIEW

**Comment by danfickle** [comment]
Thanks heaps @johnnyaug,

I have added a commit with a test and a couple of fixes. Sorry, I led you astray with bidi reordering. Not required after all as all generated list markers are ltr anyway.

Thanks again and I will merge tomorrow unless you have any objections.

**Comment by johnnyaug** [comment]
@danfickle thanks! Any chance we can release a version?

**Comment by danfickle** [comment]
I still want to fix #641 but hopefully I can release on weekend (2020-03-06ish). Thanks again @johnnyaug.

**Comment by danfickle** [comment]
1.0.7 finally released. Apologies for being very late.

**Pull request merged**
