### PR TITLE
misc cleanup: remove unused method/helper files + add missing generics

### PR DESCRIPTION
**Pull request by syjer**
This pr remove some unused helpers and a whole class (GenerateBigFile.java ).

Additionally, it finally add all the missing generic parameters + some misc. cleanups.

### CODE REVIEW

**Comment by syjer** [comment]
Btw, I'm wondering if we could cleanup a little bit the `Configuration` class. There are some features that I wonder if they are even used.

**Comment by danfickle** [comment]
Thanks, I think all the important settings are now set via the builder so we can get rid of `Configuration` class.

**Comment by syjer** [comment]
ok, this will allow to clean quite a lot of code :).

I will provide a separate PR for the refactoring of the Configuration class.

**Comment by danfickle** [comment]
Looks good, merging. Thanks again.

**Pull request merged**
