### PR TITLE
add zxing object drawer for barcode generation

### PR DESCRIPTION
**Pull request by syjer**
Hi @danfickle , this PR add the support for generating barcode using zxing directly in the pdf.

It's obviously an optional dependency in the -objects project.

### CODE REVIEW

**Comment by danfickle** [comment]
Brilliant, I think this will be useful for many. Thank you.

**Comment by syjer** [comment]
thank you, I'll write a wiki page this week end :)

**Comment by syjer** [comment]
done https://github.com/danfickle/openhtmltopdf/wiki/Plugins:-1D-2D-Barcode-with-ZXing :)

**Comment by testing138** [comment]
Eclipse cannot find "ZXingObjectDrawer" for me.

I´m using this:
```
<dependency>
  		<groupId>com.google.zxing</groupId>
  		<artifactId>javase</artifactId>
  		<version>3.4.0</version>
	</dependency>
```

**Pull request merged**
